### PR TITLE
Added support to update firmware.

### PR DESCRIPTION
**Pull request by grosssoftware**
This PR adds support for updating firmware in the CU by adding the method `ControlUnit.updatefw()`. Additionally, a new module `fw.py` has been added to easily update firmware from the command line like so:
```
python -m carreralib.fw DEVICE UPDATEFILE
```
Also, a couple small fixes have been added to support the new code:
1. Converting the `base` argument in `protocol._pack_s()` to a single byte is necessary to avoid a python exception.
2. Added handling for response `#` (unknown command) to `SerialConnection.recv()` since it can be sent by the CU, particularly when the firmware is missing.

### CODE REVIEW

**Comment by tkem** [comment]
Wow, I'm quite impressed! That's something I considered adding a long while ago, but always was too afraid to "fry" my CU trying ;-)
Code looks clean and I'll definitely want to merge this after giving it a try. I'll probably also have to add a statement to the README saying "TRY AT YOUR OWN RISK" and "no, you will _not_ get any firmware files here" before releasing ;-)

**Comment by tkem** [comment]
One question: Did you try his via a serial connection or via Bluetooth/AppConnect?

**Comment by grosssoftware** [comment]
No fried CU here. :) I agree on the disclaimers. For background, I encountered the issue where my devices would drop the BT connection to AppConnect while updating firmware with Carrera RaceApp which bricked my CU. After finding your lib, acquiring a firmware file, and jerry rigging a serial connection, I was able to reprogram my CU. I've tested a few versions of firmware over serial, but can't test BT because of the drop problem -- happens with all my iOS devices and my Raspberry Pi. Pretty sure my AppConnect is a dud that only worked with a very old version of iOS I no longer have. Since I figured out the simple programming protocol from inspecting the serial lines while attempting to update with the AppConnect, I'm fairly confident this should work over BT as well.

**Comment by tkem** [comment]
Hi @grosssoftware, and sorry for the delay - work and health issues got in the way, somehow...
After looking at the `carreralib` code after a couple of years again, I decided it was time to update/modernize some things _before_ adding new features ;-)
Especially the state of Python Bluetooth support, with `bluepy` being hopelessly outdated, and its apparent successor, `bleak` having some issues, e.g. an async API that doesn't play nicely with the current `carreralib` design...
So please bear with me, I merged your PR into a branch [https://github.com/tkem/carreralib/tree/updatefw] that's in line with current development and will eventually be part of the next release.

**Pull request closed without merging**
